### ISSUE TITLE
Complete the `create_resource_specification()`

### ISSUE THREAD

**Issue by vkatsuba** [oda-components/oda-api-ri-rust#24]
The `create_resource_specification()` should inserts the received `JSON` object into `redis` and returns a response compliant with `TMF634`.
**TODO**: expected input/output JSON data.

**Comment by vances** [comment]
Completed in commit #27.  The `create_resource_specification()` function in `tmf634_server` now inserts the entity in Redis and responds with `201 Created`:
```
$ curl -s -H 'Context-Type: application/json' -H 'Accept: application/json' --data '{"name": "example"}' http://localhost:8080/tmf-api/resourceCatalog/v4/resourceSpecification | json_pp
{
   "href" : "/tmf-api/resourceCatalog/v4/018c06b3-bc25-7613-8e9f-198dd4fd294f",
   "id" : "018c06b3-bc25-7613-8e9f-198dd4fd294f",
   "name" : "example"
}
```

The Redis command used is:  `JSON.SET resourceSpecification:<uuid> <ResourceSpecification>`
Reading the above from Redis CLI:
```
$ redis-cli
127.0.0.1:6379> JSON.GET resourceSpecification:018c06b3-bc25-7613-8e9f-198dd4fd294f
"\"{\\\"href\\\":\\\"/tmf-api/resourceCatalog/v4/018c06b3-bc25-7613-8e9f-198dd4fd294f\\\",\\\"id\\\":\\\"018c06b3-bc25-7613-8e9f-198dd4fd294f\\\",\\\"name\\\":\\\"example\\\"}\""
```
